// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYkiq8Hn6VO2PlDgoMLiLi_OFmXJ3Wr2k',
    appId: '1:419453550938:android:f2e469df90f58737def363',
    messagingSenderId: '419453550938',
    projectId: 'loksewa-app-testing',
    databaseURL: 'https://loksewa-app-testing-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'loksewa-app-testing.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDC1wRZcIbKj4aSmZMirVw3BI1YX9zM0IE',
    appId: '1:419453550938:ios:c17b24e6dfe7579cdef363',
    messagingSenderId: '419453550938',
    projectId: 'loksewa-app-testing',
    databaseURL: 'https://loksewa-app-testing-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'loksewa-app-testing.appspot.com',
    iosClientId: '419453550938-be8qtsikjemopejic2q4nd4rr3f352al.apps.googleusercontent.com',
    iosBundleId: 'com.example.loksewa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDC1wRZcIbKj4aSmZMirVw3BI1YX9zM0IE',
    appId: '1:419453550938:ios:c17b24e6dfe7579cdef363',
    messagingSenderId: '419453550938',
    projectId: 'loksewa-app-testing',
    databaseURL: 'https://loksewa-app-testing-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'loksewa-app-testing.appspot.com',
    iosClientId: '419453550938-be8qtsikjemopejic2q4nd4rr3f352al.apps.googleusercontent.com',
    iosBundleId: 'com.example.loksewa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA52mA7S4goN8LTgEBegSYgqjxnMuNaLCQ',
    appId: '1:419453550938:web:35e9f913ed1530f7def363',
    messagingSenderId: '419453550938',
    projectId: 'loksewa-app-testing',
    authDomain: 'loksewa-app-testing.firebaseapp.com',
    databaseURL: 'https://loksewa-app-testing-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'loksewa-app-testing.appspot.com',
  );

}